### ISSUE TITLE
Unable to access JACIS releases as described in Wiki

### ISSUE THREAD

**Issue by fullben** [JanWiemer/jacis#31]
I'm unable to fetch the build of this library as described in the Wiki.

Steps to reproduce:

- clone https://github.com/JanWiemer/deprecated-jacisexampleprj
- sync Gradle project
- fails with "Could not resolve: org.jacis:jacis:2.0.0-build+" (issue persists if an actual version, e.g. 2.0.10 is used)

I was able to download the artifact this way a couple weeks back, did any of the credentials/configurations change?

**Comment by JanWiemer** [comment]
Had to update the security token for public read access to the releases (unfortunately github does not allow public access to maven type packages without a token). I updated the WIKI pages with the description.

**Comment by JanWiemer** [comment]
Waiting for https://github.community/t/download-from-github-package-registry-without-authentication/14407/61 to avoid these tokens :-(

**Comment by JanWiemer** [comment]
Unfortunately github detects all commits including the token and automatically invalidates the token.
I again regenerated a new token and added a note to the documentation that this token should never be committed to github.
Sorry for the inconvenience!

**Comment by fullben** [comment]
Oh I see. In that case, I'm sorry for committing the token. I'll remove it from my project ASAP. 

I guess I'll have to rely on a prebuilt, project-included version of the library until (or if) GitHub ever changes the package registry access...
